'''
Common settings for using in a project scope
'''

S3_MODEL_PATH = 'TF_AWS_S3_MODEL_PATH'
MODEL_PROTOBUF_FILE_NAME_ENV_VAR = 'TF_AWS_MODEL_PROTOBUF_FILE_NAME'
S3_MODEL_BUCKET_NAME_ENV_VAR = 'TF_AWS_S3_MODEL_BUCKET_NAME'
